server:
  port: ${PORT:8010}
  tomcat:
    # Setting max size of post requests to 1024MB (default: 2MB)
    max-http-post-size: 1073741824

spring:
  application:
    name: message-service
  servlet:
    multipart:
      # Общий размер файла не может превышать
      max-file-size: 1024MB
      # Общий размер запроса не может превышать
      max-request-size: 1024MB
  # DataBase
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:message_service}?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    max-active: 50
    initial-size: 5
    max-idle: 10
    min-idle: 5
    test-while-idle: true
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
    test-on-borrow: true
    validation-query: SELECT 1
    # Инициализация стартовых sql команд при запуске веб-приложения из отдельного файла
    # DataSource режимы инициализации: ALWAYS, EMBEDDED, NEVER
    initialization-mode: always

  # Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: thread
        enable_lazy_load_no_trans: true
    # Включает генерацию объектов (сущностей) в БД
    generate-ddl: true
    hibernate:
      # Позволяет более подробно управлять поведением генерации в БД
      ddl-auto: update
    show-sql: false
    # читабельный SQL
    format-sql: true
  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST:smtp.mail.ru}
    protocol: ${MAIL_PROTOCOL:smtp}
    port: ${MAIL_PORT:587}
    username: ${MAIL_LOGIN:сюда почту}
    password: ${MAIL_PASSWORD:пароль от почты}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    test-connection: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: false
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    # состояние статусов по умолчанию
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

bot:
  facebook:
    app-id: app id here
    verify-token: verify token here
    page-access-token: access token here

  vk:
    auth-token: токен у граппы вк
    group-id: ид группы вк

  discord:
    auth-token: дискорд токен бота

  telegram:
    name: Имя телеграм бота
    auth-token: токен телеграм бота

notification:
  service-account-file: classpath:firebase-key.json

sms:
  login: ${SMS_LOGIN:логин}
  password: ${SMS_PASSWORD:пароль}
  is-https: ${SMS_IS_HTTPS:false}
  charset: ${SMS_CHARSET:UTF-8}
  is-post: ${SMS_IS_POST:true}
  sender:
    name: ${SMS_SENDER_NAME:ALEXEY}

application:
  max-minutes-for-send-message: 15